name: Test Build and Install

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test Build and Install
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install build
        pip install -r requirements.txt

    # Test building the package
    - name: Build the package
      run: python -m build

    # Test installation of the package
    - name: Test installation
      run: |
        pip install dist/*.whl
        python -c "import openai_json; print(openai_json.__version__)"

    # Run tests
    - name: Run tests
      run: |
        pip install pytest
        pytest tests/
